# Add application configuration variables here, as shown below.
#
development:
  AWS_ACCESS_KEY_ID: AKIAINB3JIMFHB4PR5QA
  AWS_SECRET_ACCESS_KEY: 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
  AWS_S3_BUCKET: rarian
  AWS_FILE_BUCKET: files.alphapitch.com
  DEFAULT_EMAIL: support@dejed.com
  AUTO_QUOTE_UPDATE: false
  OPSWAT_API_KEY: 50c4cb6fd12e0905a6a6a20b732b0a2e
  VIRUSTOTAL_API_KEY: 0c51d3ef49333a90a1ed961b03581892c76a295b88aec399b15efc5f6382e8d7
production:
  AWS_ACCESS_KEY_ID: AKIAINB3JIMFHB4PR5QA
  AWS_SECRET_ACCESS_KEY: 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
  AWS_S3_BUCKET: alphapitch
  AWS_FILE_BUCKET: files.alphapitch.com
  DEFAULT_EMAIL: member_services@alphapitch.com
  AUTO_QUOTE_UPDATE: true
  OPSWAT_API_KEY: 50c4cb6fd12e0905a6a6a20b732b0a2e
  VIRUSTOTAL_API_KEY: 0c51d3ef49333a90a1ed961b03581892c76a295b88aec399b15efc5f6382e8d7

