# Add application configuration variables here, as shown below.
#
development:
  AWS_ACCESS_KEY_ID: AKIAJWJIVHNPVRCRHFRQ
  AWS_SECRET_ACCESS_KEY: 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
  AWS_S3_BUCKET: rarian
  DEFAULT_EMAIL: support@dejed.com
production:
  AWS_ACCESS_KEY_ID: AKIAJWJIVHNPVRCRHFRQ
  AWS_SECRET_ACCESS_KEY: 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
  AWS_S3_BUCKET: alphapitch
  DEFAULT_EMAIL: member_services@alphapitch.com

