# Add application configuration variables here, as shown below.
#
development:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_S3_BUCKET: rarian
  AWS_FILE_BUCKET: rarefiles
  DEFAULT_EMAIL: support@dejed.com
  AUTO_QUOTE_UPDATE: false
  OPSWAT_API_KEY: 
  VIRUSTOTAL_API_KEY: 
  SOLVEMEDIA_CKEY: 
  SOLVEMEDIA_VKEY: 
  SOLVEMEDIA_HKEY: 
production:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_S3_BUCKET: alphapitch
  AWS_FILE_BUCKET: files.alphapitch.com
  DEFAULT_EMAIL: member_services@alphapitch.com
  AUTO_QUOTE_UPDATE: true
  OPSWAT_API_KEY: 
  VIRUSTOTAL_API_KEY: 
  SOLVEMEDIA_CKEY: 
  SOLVEMEDIA_VKEY: 
  SOLVEMEDIA_HKEY: 

